- hosts: all
  gather_facts: false
  connection: local
  tasks:

    - debug:
        msg: "This is the playbook verbosity: {{ ansible_verbosity }}"

    - debug:
        msg: "This a print of the vs:{{ ' -' + 'v' * ansible_verbosity if ansible_verbosity else '' }}"

    - debug:
        msg: "vebosity 1"
        verbosity: 1

    - debug:
        msg: "vebosity 2"
        verbosity: 2

    - debug:
        msg: "vebosity 3"
        verbosity: 3

    - debug:
        msg: "vebosity 4"
        verbosity: 4

    - debug:
        msg: "vebosity 5"
        verbosity: 5
