# To run this you need to set the environment variables
# ANSIBLE_GALAXY_SERVER_LIST=galaxy
# ANSIBLE_GALAXY_SERVER_GALAXY_URL=https://galaxy.ansible.com
# ANSIBLE_GALAXY_SERVER_GALAXY_TOKEN=<your token>
- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    namespace_name: alancoding
    package_name: awx
    package_version: 0.0.3
    clone_path: awx_clone
  tasks:
    - name: Checkout Alans collection branch
      git:
        repo: "https://github.com/AlanCoding/awx.git"
        dest: "{{ clone_path }}"
        version: "awx_modules_merge"
        force: yes
        depth: 1

    - name: Save location of AWX collection
      set_fact:
        collection_path: "{{ clone_path }}/awx_collection"

    - name: Template the galaxy.yml file
      template: src={{ collection_path }}/galaxy.yml.j2 dest={{ collection_path }}/galaxy.yml

    - name: build the collection
      command: ansible-galaxy collection build {{ collection_path }} --output-path={{ collection_path }} --force

    - name: Save filename of build
      set_fact:
        release_identifier: "{{ namespace_name }}-{{ package_name }}-{{ package_version }}"

    - name: Set exists message
      set_fact:
        exists_message: 'Message: Collection "{{ release_identifier }}" already exists.'

    - name: publish the collection
      command: ansible-galaxy collection publish {{ collection_path }}/{{ release_identifier }}.tar.gz
      register: publish_result
      changed_when: "'Collection has been successfully published and imported' in publish_result.stdout"
      failed_when:
        - publish_result.rc != 0
        - exists_message not in publish_result.stderr
