---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: create a disk
    gcp_compute_disk:
      name: "disk-test-vm"
      size_gb: 50
      source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts'
      type: 'pd-ssd'
      zone: us-central1-a
      project: awxengineering
      auth_kind: serviceaccount
      service_account_file: "{{ lookup('env','GCP_SERVICE_ACCOUNT_FILE') }}"
      state: absent
