---
# ansible-playbook -i localhost, is_tty.yml
# (returns false)
- hosts: all
  gather_facts: true
  connection: local
  tasks:
    - name: Determine if shell uses a tty
      shell: >
        python3 -c "import sys; print(sys.stdout.isatty())"
      register: result

    - name: Show result of that
      debug:
        msg: "stdout: {{result.stdout}}, stderr: {{result.stderr}}"

    - name: Determine if command uses a tty
      command: >
        python3 -c "import sys; print(sys.stdout.isatty())" | grep .
      register: result

    - name: Show result of that
      debug:
        msg: "stdout: {{result.stdout}}, stderr: {{result.stderr}}"

# Compare to same command ran from Makefile, `make test_tty` -> True
