---
# See documentation at
# https://docs.ansible.com/ansible-tower/latest/html/userguide/job_templates.html
- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - debug:
        msg: "{{ item }}: {{ lookup('vars', item, default='missing') }}"
      loop:
        - tower_job_id
        - tower_job_launch_type
        - tower_job_template_id
        - tower_job_template_name
        - tower_project_revision
        - tower_user_email
        - tower_user_first_name
        - tower_user_id
        - tower_user_last_name
        - tower_user_name
        - tower_schedule_name
        - tower_workflow_job_id
        - tower_workflow_job_name
        - tower_inventory_id
        - tower_inventory_name
