---
- hosts: localhost
  gather_facts: no

  tasks:
    - command: "{{ item }}"
      register: command_register
      ignore_errors: true
      no_log: True
      with_items:
        - date

    - name: debug1
      debug: var="{{command_register}}"

    - name: debug2
      debug: msg="{{ command_register.stdout }}"